version: '3.9'

services:
  postgresdb:
    image: postgres
    env_file:
      - ./.env
    ports:
      - $LOCAL_DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  backend:
    depends_on:
      - postgresdb
    image: pharsh4585/verifywise-backend:latest
    env_file:
      - ./.env
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    environment:
      - PORT=$BACKEND_PORT
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - MOCK_DATA_ON=$MOCK_DATA_ON
      - JWT_SECRET=$JWT_SECRET
  frontend:
    depends_on:
      - backend
    image: pharsh4585/verifywise-frontend:latest
    env_file:
      - ./.env
    ports:
      - $FRONTEND_PORT:80
    # environment:
    #   # backend URL
    #   - VITE_API_URL=http://localhost:${PORT}

volumes:
  db:
